server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1d9aa4r38948t42ko.mysql.rds.aliyuncs.com:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: WangWei001103
  redis:
    host: 114.115.177.60
    port: 6379
    password: ww1103
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug