---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 王为.
--- DateTime: 2022/11/8 21:13
--- Description: 实现判断锁和释放锁的原子操作
---


-- 比较线程标示与锁中的标示是否一致
if(redis.call('get', KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del', KEYS[1])
end
return 0